### ISSUE TITLE
Clustering problem

### ISSUE THREAD

**Issue by biowander** [xgrau/possvm-orthology#20]
Hell0! After running the test file with the latest version of possvm, I got completely different results compared to the example. I suspect that there might be an issue with the clustering.
![test_pro](https://github.com/user-attachments/assets/8e6ea8b8-c485-4002-a00f-ac2fa307c040)

**Comment by xgrau** [comment]
This is surprising. I'm getting the expected output. Are you sure you have the latest version?

Do you run this as is?

```bash
possvm -i test/fa_synthases.newick -p fa_synthases_unnamed
```

**Comment by biowander** [comment]
I used the same command: python possvm.py -i test/fa_synthases.newick -p fa_synthases_unnamed -o test_new. The results show that there appeared to be no issues in the previous version of possvm with duplicated entries. However, in the current version, I got some incredible results.

**Comment by biowander** [comment]
Sorry! The inconsistent results were caused by my own mistake.

**Comment by biowander** [comment]
In the https://github.com/xgrau/possvm-orthology/commit/d5fe3b563c0efc043cc6c68a7194668d198832a6 version you submitted, it seems that issue https://github.com/xgrau/possvm-orthology/issues/19 was resolved, but it appears to have caused the test files to be non-reproducible. In the latest version https://github.com/xgrau/possvm-orthology/commit/fe9ce9590b1d9c4bc09986dec6f73a1f59c80f19, issue https://github.com/xgrau/possvm-orthology/issues/19 has reappeared, while the results of the test files are correct. I'm not sure why this is happening.

**Comment by xgrau** [comment]
I see what happened. In the first fix I changed how MCL uses node weights and pruning to solve your issue, and in the second one I changed it again to fix the inconsistent labels you mentioned. I didn't realise that by doing that I reintroduced the first error because the second time I only tested the changes with a tree with node supports, whereas yours didn't have them. It should work now! (please let me know if it doesn't...)

Thanks a lot for your help!

**Comment by biowander** [comment]
This update is perfect, thank you for your help!
